name: bibliometrics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy=1.26.4
  - networkx=3.2.1
  - pandas=2.2.1
  - matplotlib=3.8.3
  - country_converter=1.2
  - pip:
      - gender_guesser==0.4
      - openchord==0.1.7
